import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Providers } from "./providers";
import { TopBar } from "~/widgets/topBar";

export const metadata: Metadata = {
  title: "CineMate",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body suppressHydrationWarning={true}>
        <Providers>
          <TopBar />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}